### ISSUE TITLE
Sunlife link outdated

### ISSUE THREAD

**Issue by grdmnt** [marvs/navfund#1]
The sunlife link for the scraper is outdated. Maybe this can help.

https://www.sunlife.com.ph/PH/Investments/NAVPS?vgnLocale=en_CA

**Comment by marvs** [comment]
Hello @grdmnt , thanks for the report. I will release a new version of the gem with the fix.

**Comment by marvs** [comment]
navfund 1.2.0 has been published. Thank you!
